### ISSUE TITLE
Is walking over AST implemented?

### ISSUE THREAD

**Issue by janmarek** [RReverser/acorn-jsx#23]
I have tried to implement a parser for finding all method calls with certain method names.

```js
var acorn = require('acorn-jsx');
var walk = require('acorn/dist/walk');

var parsed = acorn.parse(code, {
    ecmaVersion: 6,
    plugins: {jsx: true}
});

walk.simple(parsed, {
    CallExpression: (node) => {
        doSomethingWithEveryCallExpressions(node);
    }
});
```

But I only get this error:

```
TypeError: Object [object Object] has no method 'JSXElement'
    at c (/Users/janmarek/www/shipito-client/node_modules/acorn/dist/walk.js:61:15)
    at Object.skipThrough (/Users/janmarek/www/shipito-client/node_modules/acorn/dist/walk.js:180:3)
    at c (/Users/janmarek/www/shipito-client/node_modules/acorn/dist/walk.js:61:15)
    at Object.base.ReturnStatement.base.YieldExpression (/Users/janmarek/www/shipito-client/node_modules/acorn/dist/walk.js:223:22)
    at c (/Users/janmarek/www/shipito-client/node_modules/acorn/dist/walk.js:61:15)
    at Object.skipThrough (/Users/janmarek/www/shipito-client/node_modules/acorn/dist/walk.js:180:3)
    at c (/Users/janmarek/www/shipito-client/node_modules/acorn/dist/walk.js:61:15)
    at Object.base.Program.base.BlockStatement (/Users/janmarek/www/shipito-client/node_modules/acorn/dist/walk.js:191:5)
    at c (/Users/janmarek/www/shipito-client/node_modules/acorn/dist/walk.js:61:15)
    at Object.skipThrough (/Users/janmarek/www/shipito-client/node_modules/acorn/dist/walk.js:180:3)
```

Am I doing anything wrong or is it not possible to walk over AST with acorn/dist/walk?

**Comment by janmarek** [comment]
Ok. I had to use custom walk base argument.

```js
var jsxBase = merge(walk.base, {
    JSXElement(node, st, c) {
        node.openingElement.attributes.forEach((attr) => {
            c(attr, st, attr.type);
        });
        node.children.forEach((child) => {
            c(child, st, child.type);
        });
    },
    JSXExpressionContainer(node, st, c) {
        c(node.expression, st, node.expression.type);
    },
    JSXAttribute(node, st, c) {
        if (node.value !== null) {
            c(node.value, st, node.value.type);
        }
    },
    JSXSpreadAttribute(node, st, c) {
        c(node.argument, st, node.argument.type);
    }
});

walk.simple(parsed, {
    CallExpression: (node) => {
        doSomethingWithEveryCallExpressions(node);
    }
}, jsxBase);
```

I am keeping this open because I think it should be working out of the box.

**Comment by RReverser** [comment]
There is plenty of tools for walking over AST including `ast-types`, `babel-core` etc. I don't really think it needs to be part of parser.

**Comment by janmarek** [comment]
It is a part of original acorn. But it obviously does not work for JSX.

**Comment by arendjr** [comment]
Just ran into this and I'm quite bumped this is not part of this package. Walking is a core feature of Acorn, and this is a plugin for Acorn, but as it is it just leaves you with a broken experience when it comes to walking. I learned there's `acorn-jsx-walk`, which offers an incomplete experience as well, so I'm down to patching it myself thanks to @janmarek's comment.

**Comment by arendjr** [comment]
For the next guy, this is the snippet I ended up using to be able to walk over all call expressions:

```js
Object.assign(walk.base, {
    JSXAttribute(node, state, callback) {
        if (node.value !== null) {
            callback(node.value, state);
        }
    },

    JSXElement(node, state, callback) {
        node.openingElement.attributes.forEach(attribute => {
            callback(attribute, state);
        });
        node.children.forEach(node => {
            callback(node, state);
        });
    },

    JSXExpressionContainer(node, state, callback) {
        callback(node.expression, state);
    },

    JSXFragment(node, state, callback) {
        node.children.forEach(node => {
            callback(node, state);
        });
    },

    JSXSpreadAttribute(node, state, callback) {
        callback(node.argument, state);
    },

    JSXText() {}
});
```
